name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: publish airmiss
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Airmiss/Airmiss.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}  
  
    - name: publish airmiss http
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Airmiss.Protocol.Http/Airmiss.Protocol.Http.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        
    - name: publish airmiss websocket
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Airmiss.Protocol.Http/Airmiss.Protocol.Websocket.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
